// Classificação de produtos por categoria a partir do nome.
//
// Por que um classificador e não uma coluna digitada: 500 produtos digitados à
// mão viram 500 decisões soltas, e ninguém revisa a categoria do item 431. Aqui a
// categoria é *derivada* da fonte, de forma determinística — o mesmo nome cai
// sempre na mesma categoria — e `data/produtos.csv` guarda o resultado para que
// uma decisão manual continue possível quando o classificador errar.
//
// O arquivo é puro (sem Vue, sem DOM) porque é usado tanto pelo importador,
// fora do Vite, quanto pelos testes.
//
// Três modos de casamento, porque cada um evita uma classe de erro:
//
//   palavra  — o termo precisa ser um token inteiro. "casa" NÃO casa "casaco".
//   prefixo  — o token começa com o termo. "fone" casa "fones", "smartwatch".
//   texto    — o termo aparece em qualquer lugar, inclusive atravessando
//              palavra. Só para expressões compostas ("kit Complete").
//
// A ordem das regras importa: vence a primeira que casar. Por isso
// "pet" vem antes de "beleza" (shampoo de cachorro é pet, não beleza) e
// "eletronicos" vem antes de "fitness" (fone gamer de academia é eletrônico).

import { normalizar } from './format.js'

export const MODO_PALAVRA = 'palavra'
export const MODO_PREFIXO = 'prefixo'
export const MODO_TEXTO = 'texto'

/** Tokens do nome já normalizados: sem acento, minúsculo, sem pontuação nas bordas. */
export function tokenizar(nome) {
  return normalizar(nome)
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
}

function casa(tokens, termo, modo) {
  const alvo = normalizar(termo).replace(/[^a-z0-9]+/g, ' ').trim()

  // Termo que degenera para vazio é erro de digitação, não palavra. O pior caso
  // visto foi 'po:', que vira o substring 'po' e passa a casar com "Polo",
  // "Imposto" e qualquer outro nome que contenha essas duas letras.
  if (!alvo) return false

  // O texto precisa vir normalizado dos dois lados: "máscara facial" contra os
  // tokens já sem acento nunca casaria.
  if (modo === MODO_TEXTO) {
    return tokens.join(' ').includes(alvo)
  }

  if (modo === MODO_PREFIXO) {
    return tokens.some((t) => t.startsWith(alvo))
  }

  return tokens.includes(alvo)
}

/**
 * Regras em ordem de prioridade. Só entra aqui o que se aplica a um nome real de
 * produto; regra vaga demais captura categoria errada silenciosamente, que é
 * pior do que cair em "outros".
 */
export const REGRAS_CATEGORIA = [
  {
    id: 'pet',
    termos: [
      ['pet', MODO_PALAVRA],
      ['cachorr', MODO_PREFIXO],
      ['gato', MODO_PALAVRA],
      ['gatos', MODO_PALAVRA],
      ['cães', MODO_PALAVRA],
      ['cao', MODO_PALAVRA],
      ['hamster', MODO_PREFIXO],
      ['coelho', MODO_PALAVRA],
      ['papagaio', MODO_PALAVRA],
      ['tartaruga', MODO_PALAVRA],
      ['aquario', MODO_PALAVRA],
      ['antipulgas', MODO_PALAVRA],
      ['vermífugo', MODO_TEXTO],
      ['coleira', MODO_PALAVRA],
      ['comedouro', MODO_PALAVRA],
      ['brinquedo para ca', MODO_TEXTO],
      ['areia para gato', MODO_TEXTO],
    ],
  },
  {
    id: 'infantil',
    termos: [
      ['infantil', MODO_PALAVRA],
      ['crianc', MODO_PREFIXO],
      ['bebe', MODO_PALAVRA],
      ['kit bebe', MODO_TEXTO],
      ['fralda', MODO_PREFIXO],
      ['mamadeira', MODO_PALAVRA],
      ['chupeta', MODO_PALAVRA],
      ['carrinho de bebe', MODO_TEXTO],
      ['brinquedo', MODO_PREFIXO],
      ['brinquedos', MODO_PREFIXO],
      ['boneca', MODO_PREFIXO],
      ['boneco', MODO_PREFIXO],
      ['quebra-cabeca', MODO_TEXTO],
      ['massinha', MODO_PALAVRA],
      ['plastilina', MODO_PALAVRA],
      ['kids', MODO_PALAVRA],
      ['nerf', MODO_PALAVRA],
      ['blaster', MODO_PALAVRA],
    ],
  },
  {
    id: 'automotivo',
    termos: [
      ['automotiv', MODO_PREFIXO],
      ['veicul', MODO_PREFIXO],
      ['carro', MODO_PALAVRA],
      ['moto', MODO_PREFIXO],
      ['motociclist', MODO_PREFIXO],
      ['motoqueir', MODO_PREFIXO],
      ['farol', MODO_PALAVRA],
      ['retrovisor', MODO_PALAVRA],
      ['para-brisa', MODO_TEXTO],
      ['parabrisa', MODO_PALAVRA],
      ['bateria', MODO_PALAVRA],
      ['oleo de motor', MODO_TEXTO],
      ['graxa', MODO_PALAVRA],
      ['pneu', MODO_PALAVRA],
      ['pneus', MODO_PALAVRA],
      ['chave de fenda', MODO_TEXTO],
      ['racao', MODO_PALAVRA],
      ['estetica automotiva', MODO_TEXTO],
      ['polimento', MODO_PALAVRA],
      ['tinta automotiva', MODO_TEXTO],
      ['desembaçador', MODO_PALAVRA],
      ['transmissao', MODO_PALAVRA],
      ['tracao', MODO_PALAVRA],
      ['relacao', MODO_PALAVRA],
    ],
  },
  {
    id: 'ferramentas',
    termos: [
      ['ferramenta', MODO_PREFIXO],
      ['broca', MODO_PALAVRA],
      ['chave allen', MODO_TEXTO],
      ['parafuso', MODO_PREFIXO],
      ['furadeira', MODO_PALAVRA],
      ['silicone vedante', MODO_TEXTO],
      ['trena', MODO_PALAVRA],
      ['multimetro', MODO_PALAVRA],
      ['alicate', MODO_PALAVRA],
      ['fita isolante', MODO_TEXTO],
      ['jogo de chave', MODO_TEXTO],
      ['kit ferramenta', MODO_TEXTO],
      ['bico de corte', MODO_TEXTO],
      ['rebitadeira', MODO_PALAVRA],
      ['chaves', MODO_PALAVRA],
      ['catraca', MODO_PALAVRA],
      ['soquete sextavado', MODO_TEXTO],
      ['esmerilhadeira', MODO_PALAVRA],
      ['chave de impacto', MODO_TEXTO],
      ['disco de corte', MODO_TEXTO],
      ['flap', MODO_PALAVRA],
    ],
  },
  {
    id: 'saude',
    termos: [
      ['vitamina', MODO_PREFIXO],
      ['massageador', MODO_PREFIXO],
      ['massagem', MODO_PALAVRA],
      ['acucar mofologico', MODO_TEXTO],
    ],
  },
  {
    id: 'eletronicos',
    termos: [
      ['fone', MODO_PREFIXO],
      ['fone de ouvido', MODO_TEXTO],
      ['fones de ouvido', MODO_TEXTO],
      ['headset', MODO_PALAVRA],
      ['earphone', MODO_PALAVRA],
      ['airpods', MODO_PALAVRA],
      ['bluetooth', MODO_PALAVRA],
      ['carregador', MODO_PALAVRA],
      ['power bank', MODO_TEXTO],
      ['cabo', MODO_PALAVRA],
      ['impressora', MODO_PALAVRA],
      ['smartwatch', MODO_PREFIXO],
      ['relógio inteligente', MODO_TEXTO],
      ['smartphone', MODO_PALAVRA],
      ['notebook', MODO_PALAVRA],
      ['teclado', MODO_PALAVRA],
      ['mouse', MODO_PALAVRA],
      ['monitor', MODO_PALAVRA],
      ['caixa de som', MODO_TEXTO],
      ['speaker', MODO_PALAVRA],
      ['microfone', MODO_PALAVRA],
      ['camera', MODO_PALAVRA],
      ['selfie', MODO_PALAVRA],
      ['ring light', MODO_TEXTO],
      ['led', MODO_PALAVRA],
      ['drone', MODO_PALAVRA],
      ['tripe', MODO_PALAVRA],
      ['adaptador', MODO_PALAVRA],
      ['hdmi', MODO_PALAVRA],
      ['usb', MODO_PALAVRA],
      ['bateria externa', MODO_TEXTO],
      ['projetor', MODO_PALAVRA],
      ['tablet', MODO_PALAVRA],
      ['console', MODO_PALAVRA],
      ['controle remoto', MODO_TEXTO],
      ['mata mosquito', MODO_TEXTO],
      ['abajur', MODO_PALAVRA],
      ['luminaria', MODO_PALAVRA],
      ['lampada', MODO_PALAVRA],
      ['termometro', MODO_PALAVRA],
      ['balança digital', MODO_TEXTO],
      ['alto falante', MODO_TEXTO],
      ['smart watch', MODO_TEXTO],
      ['lupa', MODO_PALAVRA],
      ['amplificador', MODO_PALAVRA],
    ],
  },
  {
    id: 'casa-e-cozinha',
    termos: [
      ['forma de silicone', MODO_TEXTO],
      ['forma para', MODO_TEXTO],
      ['molde', MODO_PALAVRA],
      ['cesto de silicone', MODO_TEXTO],
      ['kit forma', MODO_TEXTO],
      ['forma', MODO_PALAVRA],
    ],
  },
  {
    id: 'eletrodomesticos',
    termos: [
      ['air fryer', MODO_TEXTO],
      ['airfryer', MODO_TEXTO],
      ['fritadeira', MODO_PREFIXO],
      ['cafeteira', MODO_PALAVRA],
      ['liquidificador', MODO_PALAVRA],
      ['processador', MODO_PALAVRA],
      ['mixer', MODO_PALAVRA],
      ['batedeira', MODO_PALAVRA],
      ['aspirador', MODO_PALAVRA],
      ['par robotic', MODO_TEXTO],
      ['lava e seca', MODO_TEXTO],
      ['lava e seque', MODO_TEXTO],
      ['maquina de lavar', MODO_TEXTO],
      ['geladeira', MODO_PALAVRA],
      ['micro-ondas', MODO_TEXTO],
      ['microondas', MODO_PALAVRA],
      ['forno', MODO_PALAVRA],
      ['cooktop', MODO_PALAVRA],
      ['pipoqueira', MODO_PALAVRA],
      ['sanduicheira', MODO_PALAVRA],
      ['sandwich', MODO_PALAVRA],
      ['waffle maker', MODO_TEXTO],
      ['descafeineador', MODO_PALAVRA],
      ['purificador', MODO_PALAVRA],
      ['filtro de agua', MODO_TEXTO],
      ['máquina de gelo', MODO_TEXTO],
      ['ventilador', MODO_PALAVRA],
      ['climatizador', MODO_PALAVRA],
      ['desumidificador', MODO_PALAVRA],
      ['purificador de ar', MODO_TEXTO],
      ['cortador', MODO_PALAVRA],
      ['coifa', MODO_PALAVRA],
      ['fogao', MODO_PALAVRA],
      ['chaleira', MODO_PREFIXO],
      ['omeleteira', MODO_PALAVRA],
      ['cozedor', MODO_PALAVRA],
      ['escova eletrica', MODO_TEXTO],
      ['esfregador', MODO_PALAVRA],
      ['lavadora', MODO_PALAVRA],
      ['iogurteira', MODO_PALAVRA],
      ['torradeira', MODO_PALAVRA],
    ],
  },
  {
    id: 'casa-e-cozinha',
    termos: [
      ['panela', MODO_PREFIXO],
      ['frigideira', MODO_PALAVRA],
      ['travessa', MODO_PALAVRA],
      ['pote', MODO_PREFIXO],
      ['potes', MODO_PREFIXO],
      ['tupperware', MODO_PALAVRA],
      ['garrafa termica', MODO_TEXTO],
      ['copo', MODO_PREFIXO],
      ['caneca', MODO_PREFIXO],
      ['mug', MODO_PALAVRA],
      ['talher', MODO_PREFIXO],
      ['garfo', MODO_PALAVRA],
      ['faca', MODO_PALAVRA],
      ['tábua', MODO_PALAVRA],
      ['prato', MODO_PREFIXO],
      ['tigela', MODO_PALAVRA],
      ['organizador', MODO_PALAVRA],
      ['armazenamento', MODO_PALAVRA],
      ['esponja', MODO_PALAVRA],
      ['detergente', MODO_PALAVRA],
      ['sabao', MODO_PALAVRA],
      ['desinfetante', MODO_PALAVRA],
      ['amaciante', MODO_PALAVRA],
      ['desodorante', MODO_PALAVRA],
      ['agua sanitaria', MODO_TEXTO],
      ['alcool', MODO_PALAVRA],
      ['limpa vidro', MODO_TEXTO],
      ['repelente', MODO_PALAVRA],
      ['inseticida', MODO_PALAVRA],
      ['mop', MODO_PALAVRA],
      ['rodo', MODO_PALAVRA],
      ['vassoura', MODO_PALAVRA],
      ['cesto de lixo', MODO_TEXTO],
      ['lixeira', MODO_PALAVRA],
      ['saco de lixo', MODO_TEXTO],
      ['papel higienico', MODO_TEXTO],
      ['sabonete', MODO_PALAVRA],
      ['kit limpeza', MODO_TEXTO],
      ['cesto', MODO_PALAVRA],
      ['porta pano', MODO_TEXTO],
      ['dispenser', MODO_PALAVRA],
      ['jarra', MODO_PALAVRA],
      ['tartela', MODO_PALAVRA],
      ['filme plastic', MODO_TEXTO],
      ['papel-aluminio', MODO_TEXTO],
      ['manta termica', MODO_TEXTO],
      ['tampo', MODO_PALAVRA],
      ['kit 6 forma', MODO_TEXTO],
      ['utensilios', MODO_PREFIXO],
      ['taca', MODO_PALAVRA],
      ['tacas', MODO_PALAVRA],
      ['bacia', MODO_PREFIXO],
      ['bacias', MODO_PREFIXO],
      ['torneira', MODO_PALAVRA],
      ['coador', MODO_PALAVRA],
      ['abridor', MODO_PREFIXO],
      ['amolador', MODO_PALAVRA],
      ['descascador', MODO_PREFIXO],
      ['petisqueira', MODO_PREFIXO],
      ['ralador', MODO_PALAVRA],
      ['fatiador', MODO_PALAVRA],
      ['percarbonato', MODO_PALAVRA],
      ['limpa gordura', MODO_TEXTO],
      ['termica', MODO_PREFIXO],
      ['cha', MODO_PALAVRA],
      ['mangueira', MODO_PALAVRA],
      ['papel toalha', MODO_TEXTO],
    ],
  },
  {
    id: 'casa-e-decoracao',
    termos: [
      ['toalha', MODO_PREFIXO],
      ['lenco', MODO_PREFIXO],
      ['colcha', MODO_PREFIXO],
      ['cobre leito', MODO_TEXTO],
      ['cama', MODO_PALAVRA],
      ['cabeceira', MODO_PALAVRA],
      ['sofa cama', MODO_TEXTO],
      ['guarda roupa', MODO_TEXTO],
      ['varal', MODO_PALAVRA],
      ['tapete', MODO_PALAVRA],
      ['espelho', MODO_PALAVRA],
      ['moldura', MODO_PALAVRA],
      ['porta retrato', MODO_TEXTO],
      ['cachepot', MODO_PALAVRA],
      ['arvore de natal', MODO_TEXTO],
      ['arvore natal', MODO_TEXTO],
      ['almofada', MODO_PALAVRA],
      ['jogo americano', MODO_TEXTO],
      ['cadeira gamer', MODO_TEXTO],
      ['cadeira de escritorio', MODO_TEXTO],
      ['mesa de jantar', MODO_TEXTO],
      ['mesa', MODO_PALAVRA],
      ['escrivaninha', MODO_PALAVRA],
      ['home office', MODO_TEXTO],
      ['naval', MODO_PALAVRA],
      ['fechadura', MODO_PALAVRA],
      ['cadeado', MODO_PALAVRA],
      ['gancho', MODO_PALAVRA],
      ['placa', MODO_PALAVRA],
      ['revestimento', MODO_PALAVRA],
      ['vaso', MODO_PALAVRA],
      ['decorac', MODO_PREFIXO],
      ['decorativ', MODO_PREFIXO],
      ['florera', MODO_PALAVRA],
      ['quadro', MODO_PALAVRA],
      ['cortina', MODO_PALAVRA],
      ['travesseiro', MODO_PALAVRA],
      ['cobertor', MODO_PALAVRA],
      ['edredom', MODO_PALAVRA],
      ['lencol', MODO_PALAVRA],
      ['colchao', MODO_PALAVRA],
      ['capinha de sofa', MODO_TEXTO],
    ],
  },
  {
    id: 'beleza',
    termos: [
      ['shampoo', MODO_PALAVRA],
      ['condicionador', MODO_PALAVRA],
      ['hidratante', MODO_PALAVRA],
      ['sabonete facial', MODO_TEXTO],
      ['mascara facial', MODO_TEXTO],
      ['sachê', MODO_PALAVRA],
      ['creme', MODO_PALAVRA],
      ['protetor solar', MODO_TEXTO],
      ['fps', MODO_PALAVRA],
      ['perfume', MODO_PALAVRA],
      ['maquiagem', MODO_PALAVRA],
      ['batom', MODO_PALAVRA],
      ['base', MODO_PALAVRA],
      ['delineador', MODO_PALAVRA],
      ['sombra', MODO_PALAVRA],
      ['cilios', MODO_PALAVRA],
      ['unha', MODO_PALAVRA],
      ['unha postiça', MODO_TEXTO],
      ['escova de cabelo', MODO_TEXTO],
      ['secador de cabelo', MODO_TEXTO],
      ['prancha de cabelo', MODO_TEXTO],
      ['chapeira', MODO_PALAVRA],
      ['barbear', MODO_PALAVRA],
      ['depiladora', MODO_PALAVRA],
      ['aparador', MODO_PALAVRA],
      ['kit de skincare', MODO_TEXTO],
      ['skincare', MODO_PALAVRA],
      ['colageno', MODO_PALAVRA],
      ['acucar morfologico', MODO_TEXTO],
      ['suplemento', MODO_PALAVRA],
      ['termogenico', MODO_PALAVRA],
      ['melatonina', MODO_PALAVRA],
      ['serum', MODO_PALAVRA],
      ['kits de manicure', MODO_TEXTO],
      ['manicure', MODO_PALAVRA],
      ['siage', MODO_PALAVRA],
      ['secador', MODO_PALAVRA],
      ['secadora', MODO_PALAVRA],
      ['frizz', MODO_TEXTO],
      ['progressiva', MODO_PALAVRA],
      ['hidratacao', MODO_PALAVRA],
      ['reconstrucao', MODO_PALAVRA],
      ['renovador', MODO_PREFIXO],
      ['esfoliadora', MODO_PALAVRA],
      ['psyllium', MODO_PALAVRA],
      ['cha verde', MODO_TEXTO],
      ['clareador', MODO_PALAVRA],
      ['perfumes', MODO_PALAVRA],
      ['facial', MODO_PALAVRA],
      ['sobrancelha', MODO_PALAVRA],
      ['revelacao', MODO_PALAVRA],
    ],
  },
  {
    id: 'calcados',
    termos: [
      ['tenis', MODO_PREFIXO],
      ['chinelo', MODO_PALAVRA],
      ['sandalia', MODO_PREFIXO],
      ['sapato', MODO_PALAVRA],
      ['sapatilha', MODO_PALAVRA],
      ['bota', MODO_PREFIXO],
      ['coturno', MODO_PALAVRA],
      ['meia', MODO_PREFIXO],
      ['soquete', MODO_PALAVRA],
      ['capa de chuva', MODO_TEXTO],
      ['kit panturrilha', MODO_TEXTO],
      ['panturrilha', MODO_PALAVRA],
      ['palmilha', MODO_PALAVRA],
      ['shoes', MODO_PALAVRA],
    ],
  },
  {
    id: 'moda-feminina',
    termos: [
      ['feminin', MODO_PREFIXO],
      ['mulher', MODO_PREFIXO],
      ['vestido', MODO_PALAVRA],
      ['saia', MODO_PALAVRA],
      ['blusa', MODO_PALAVRA],
      ['camisa feminina', MODO_TEXTO],
      ['camiseta', MODO_PALAVRA],
      ['regata', MODO_PALAVRA],
      ['cropped', MODO_PALAVRA],
      ['sutia', MODO_PALAVRA],
      ['lingerie', MODO_PALAVRA],
      ['body', MODO_PALAVRA],
      ['bermuda', MODO_PALAVRA],
      ['short', MODO_PALAVRA],
      ['macacao', MODO_PREFIXO],
      ['jaqueta', MODO_PALAVRA],
      ['casaco', MODO_PALAVRA],
      ['cobertor de cama', MODO_TEXTO],
      ['pijama', MODO_PALAVRA],
      ['bolsa', MODO_PALAVRA],
      ['mochila', MODO_PALAVRA],
      ['carteira', MODO_PALAVRA],
      ['joelheira', MODO_PALAVRA],
      ['modelador de corpo', MODO_TEXTO],
      ['modelador', MODO_PALAVRA],
      ['cinturao', MODO_PALAVRA],
      ['alfaiataria', MODO_PALAVRA],
      ['ribana', MODO_PALAVRA],
      ['tactel', MODO_PALAVRA],
      ['suplex', MODO_PALAVRA],
      ['plus size', MODO_TEXTO],
      ['maternity', MODO_PALAVRA],
      ['gestante', MODO_PALAVRA],
      ['calcinha', MODO_PREFIXO],
      ['camisola', MODO_PALAVRA],
      ['roupao', MODO_PALAVRA],
      ['espartilho', MODO_PALAVRA],
      ['cinta modeladora', MODO_TEXTO],
      ['cinta', MODO_PALAVRA],
      ['bobojaco', MODO_PALAVRA],
    ],
  },
  {
    id: 'moda-masculina',
    termos: [
      ['masculin', MODO_PREFIXO],
      ['homem', MODO_PREFIXO],
      ['cueca', MODO_PREFIXO],
      ['camiseta masculina', MODO_TEXTO],
      ['camisa masculina', MODO_TEXTO],
      ['camisa', MODO_PALAVRA],
      ['polo', MODO_PALAVRA],
      ['bermuda masculina', MODO_TEXTO],
      ['calca', MODO_PREFIXO],
      ['jeans', MODO_PALAVRA],
      ['moletom', MODO_PALAVRA],
      ['camisa polo', MODO_TEXTO],
    ],
  },
  {
    id: 'fitness',
    termos: [
      ['fitness', MODO_PALAVRA],
      ['academia', MODO_PALAVRA],
      ['treino', MODO_PALAVRA],
      ['musculacao', MODO_PALAVRA],
      ['maleta de treino', MODO_TEXTO],
      ['garrafa de academia', MODO_TEXTO],
      ['tapete de yoga', MODO_TEXTO],
      ['yoga', MODO_PALAVRA],
      ['pilates', MODO_PALAVRA],
      ['corrida', MODO_PALAVRA],
      ['ciclismo', MODO_PALAVRA],
      ['bike', MODO_PALAVRA],
      ['cadeira de musculacao', MODO_TEXTO],
      ['cadeira de treino', MODO_TEXTO],
      ['pistola de massagem', MODO_TEXTO],
      ['roldo', MODO_PALAVRA],
      ['haltere', MODO_PALAVRA],
      ['skate', MODO_PALAVRA],
      ['bicicleta', MODO_PALAVRA],
      ['patinete', MODO_PALAVRA],
      ['natação', MODO_PALAVRA],
      ['mergulho', MODO_PALAVRA],
      ['protetor de Joelho', MODO_TEXTO],
      ['caneleira', MODO_PALAVRA],
      ['creatina', MODO_PALAVRA],
    ],
  },
  {
    id: 'camping-viagem',
    termos: [
      ['camping', MODO_PALAVRA],
      ['campismo', MODO_PALAVRA],
      ['cooler', MODO_PALAVRA],
      ['maca de descanso', MODO_TEXTO],
      ['maca inflavel', MODO_TEXTO],
      ['tenda', MODO_PALAVRA],
      ['saco de dormir', MODO_TEXTO],
      ['mochila de viagem', MODO_TEXTO],
      ['mala de viagem', MODO_TEXTO],
      ['passador', MODO_PALAVRA],
      ['travel', MODO_PALAVRA],
      ['viagem', MODO_PALAVRA],
      ['roda de scorch', MODO_TEXTO],
      ['bolinha de praia', MODO_TEXTO],
      ['piscina', MODO_PALAVRA],
      ['churrasqueira', MODO_PALAVRA],
      ['guarda chuva', MODO_TEXTO],
    ],
  },
  {
    id: 'papelaria',
    termos: [
      ['papelaria', MODO_PALAVRA],
      ['caderno', MODO_PALAVRA],
      ['caneta', MODO_PREFIXO],
      ['lpis', MODO_PREFIXO],
      ['lápis', MODO_PREFIXO],
      ['apontador', MODO_PALAVRA],
      ['estojo', MODO_PALAVRA],
      ['agenda', MODO_PALAVRA],
      ['bloco', MODO_PALAVRA],
      ['adesivo', MODO_PALAVRA],
      ['cola', MODO_PALAVRA],
      ['tesoura', MODO_PALAVRA],
      ['giz', MODO_PALAVRA],
      ['massinha de modelar', MODO_TEXTO],
    ],
  },
  {
    id: 'livros',
    termos: [
      ['livro', MODO_PREFIXO],
      ['livros', MODO_PREFIXO],
      ['biblia', MODO_PREFIXO],
      ['devocional', MODO_PALAVRA],
      ['harry potter', MODO_TEXTO],
      ['infantil livro', MODO_TEXTO],
    ],
  },
]
export const CATEGORIA_PADRAO = 'outros'

/**
 * Categoria de um produto pelo nome. Devolve o id da primeira regra que casar,
 * ou `padrao` quando nada casa — cair em "outros" é honesto; errar a categoria
 * manda o produto para uma prateleira que não é a dele e derruba a confiança em
 * toda a vitrine.
 */
export function categorizar(nome, { padrao = CATEGORIA_PADRAO } = {}) {
  if (!nome || typeof nome !== 'string') return padrao

  const tokens = tokenizar(nome)
  if (!tokens.length) return padrao

  for (const regra of REGRAS_CATEGORIA) {
    for (const [termo, modo] of regra.termos) {
      if (casa(tokens, termo, modo)) return regra.id
    }
  }

  return padrao
}

/** Categorias de todos os nomes, preservando a ordem de entrada. */
export function categorizarTodos(nomes, opcoes) {
  return nomes.map((nome) => categorizar(nome, opcoes))
}